package com.glicocalc.database

// Default foods are stored in English. This table supplies the Romanian display names.
object DefaultFoodNames {
    private val englishToRomanian = mapOf(
        "White Bread" to "Pâine Albă",
        "Whole Wheat Bread" to "Pâine Integrală",
        "Rye Bread" to "Pâine de Secară",
        "Seeded Bread" to "Pâine cu Semințe",
        "Toast Bread" to "Pâine Toast",
        "Pretzel" to "Covrig",
        "Polenta" to "Mămăligă",
        "White Rice (boiled)" to "Orez Alb (fiert)",
        "Brown Rice (boiled)" to "Orez Brun (fiert)",
        "White Rice (raw)" to "Orez Alb (crud)",
        "Brown Rice (raw)" to "Orez Brun (crud)",
        "Pasta (cooked)" to "Paste (fierte)",
        "Pasta (dry)" to "Paste (crude)",
        "Couscous (boiled)" to "Cuscus (fiert)",
        "Couscous (dry)" to "Cuscus (uscat)",
        "Buckwheat (cooked)" to "Hrișcă (fiartă)",
        "Buckwheat (raw)" to "Hrișcă (crudă)",
        "Lentils (boiled)" to "Linte (fiartă)",
        "Lentils (raw)" to "Linte (crudă)",
        "Semolina" to "Griș",
        "Oat Flakes" to "Fulgi de ovăz",
        "Breadcrumbs" to "Pesmet",
        "Wheat Flour" to "Făină de grâu",
        "Whole Wheat Flour" to "Făină Integrală",
        "Cornmeal" to "Mălai",
        "Rye Flour" to "Făină de Secară",
        "Millet Flour" to "Făină de Mei",
        "French Baguette" to "Baghetă Franceză",
        "Bread Roll" to "Chiflă",
        "Flatbread" to "Lipie",
        "Polenta (soft)" to "Mămăligă (moale)",
        "Quinoa (cooked)" to "Quinoa (fiartă)",
        "Quinoa (raw)" to "Quinoa (crudă)",
        "Rice Flour" to "Făină de Orez",
        "Corn Starch" to "Amidon de Porumb",
        "Breading (Breadcrumbs/Egg)" to "Pané (pesmet/ou)",
        "Potato (boiled)" to "Cartofi (fierți)",
        "French Fries (home-cooked)" to "Cartofi pai (acasă)",
        "French Fries (fast food)" to "Cartofi pai (fast-food)",
        "Potato (baked)" to "Cartofi (copți)",
        "Carrot (raw)" to "Morcov (crud)",
        "Carrot (boiled)" to "Morcov (fiert)",
        "Peas (canned)" to "Mazăre (conservă)",
        "Green Peas (raw)" to "Mazăre verde (crudă)",
        "Beans (boiled)" to "Fasole boabe fiartă",
        "Green Beans" to "Fasole verde",
        "Soybeans (boiled)" to "Soia (fiartă)",
        "Soybeans (raw)" to "Soia (crudă)",
        "Tomato" to "Roșie",
        "Cucumber" to "Castravete",
        "Pickled Cucumber" to "Castravete (murat)",
        "Cucumber in Sweet and Sour Sauce" to "Castravete în sos dulce-acrișor",
        "Green Tomato" to "Gogonea",
        "Bell Pepper" to "Ardei gras",
        "Hot Pepper" to "Ardei iute",
        "Pickled Hot Pepper" to "Ardei iute (murat)",
        "Red Bell Pepper" to "Gogoșar",
        "Onion" to "Ceapă",
        "Cabbage (raw)" to "Varză (crudă)",
        "Cabbage (boiled)" to "Varză (fiartă)",
        "Brussels Sprouts" to "Varză de Bruxelles",
        "Broccoli (raw)" to "Broccoli (crud)",
        "Broccoli (boiled)" to "Broccoli (fiert)",
        "Cauliflower (raw)" to "Conopidă (crudă)",
        "Cauliflower (boiled)" to "Conopidă (fiartă)",
        "Kohlrabi (raw)" to "Gulie (crudă)",
        "Kohlrabi (boiled)" to "Gulie (fiartă)",
        "Parsnip (boiled)" to "Păstârnac (fiert)",
        "Parsnip (raw)" to "Păstârnac (crud)",
        "Zucchini" to "Dovlecel",
        "Eggplant" to "Vânătă",
        "Mushroom" to "Ciuperci",
        "Button Mushroom (raw)" to "Ciuperci Champignon (crude)",
        "Mushroom (canned)" to "Ciuperci (conservă)",
        "Pickled Mushroom" to "Ciuperci murate",
        "Spinach" to "Spanac",
        "Swiss Chard (boiled)" to "Mangold (fiert)",
        "Nettle" to "Urzică",
        "Orache" to "Lobodă",
        "Garden Sorrel" to "Ștevie",
        "Corn (canned)" to "Porumb (conservă)",
        "Corn (boiled)" to "Porumb fiert",
        "Sweet Corn (raw)" to "Porumb dulce (crud)",
        "Beetroot (boiled)" to "Sfeclă roșie (fiartă)",
        "Beetroot (raw)" to "Sfeclă roșie (crudă)",
        "Garlic" to "Usturoi",
        "Avocado" to "Avocado",
        "Olive (green/black)" to "Măsline (verzi/negre)",
        "Dried Olive" to "Măsline uscate",
        "Chickpeas (boiled)" to "Năut (fiert)",
        "Mashed Potato" to "Piure de cartofi",
        "Sweet Potato" to "Cartofi dulci",
        "Pumpkin" to "Dovleac",
        "Leek" to "Praz",
        "Celeriac (raw)" to "Țelină (rădăcină crudă)",
        "Chickpeas (raw)" to "Năut (crud)",
        "Beans (raw)" to "Fasole Boabe (crudă)",
        "Potato (raw)" to "Cartofi (cruzi)",
        "Sweet Potato (raw)" to "Cartofi dulci (cruzi)",
        "Apple" to "Măr",
        "Banana" to "Banană",
        "Orange" to "Portocală",
        "Blood Orange" to "Portocală Sanguinello",
        "Mandarin" to "Mandarină",
        "Clementine" to "Clementină",
        "Pear" to "Pară",
        "Grapes" to "Struguri",
        "Strawberry" to "Căpșuni",
        "Strawberry (canned)" to "Căpșuni (conservă)",
        "Blueberry" to "Afine",
        "Raspberries" to "Zmeură",
        "Peach" to "Piersică",
        "Dried Peach" to "Piersică uscată",
        "Apricot" to "Caisă",
        "Dried Apricot" to "Caise uscate",
        "Plum" to "Prună",
        "Watermelon" to "Pepene roșu",
        "Melon" to "Pepene galben",
        "Kiwi" to "Kiwi",
        "Pineapple" to "Ananas",
        "Lemon" to "Lămâie",
        "Dried Date / Fig" to "Curmale / Smochine (uscate)",
        "Dried Date" to "Curmale uscate",
        "Dried Fig" to "Smochine uscate",
        "Raisin" to "Stafide",
        "Grapefruit" to "Grepfrut",
        "Blackberry" to "Mure",
        "Blackcurrant" to "Coacăze negre",
        "Redcurrant" to "Coacăze roșii",
        "White Currant" to "Coacăze albe",
        "Honeysuckle Berry" to "Lonicera",
        "Rose Hip" to "Măceșe",
        "Pomegranate" to "Rodie",
        "Mango" to "Mango",
        "Papaya" to "Papaya",
        "Passion Fruit" to "Fructul Passion",
        "Fresh Fig" to "Smochină proaspătă",
        "Green Fig" to "Smochină verde",
        "Milk" to "Lapte",
        "Condensed Milk (unsweetened)" to "Lapte condensat (fără zahăr)",
        "Plain Yogurt" to "Iaurt natur",
        "Greek Yogurt" to "Iaurt Grecesc",
        "Sweetened Fruit Yogurt" to "Iaurt cu fructe și zahăr",
        "Drinking Yogurt (sweetened)" to "Iaurt de băut (îndulcit)",
        "Cottage Cheese" to "Brânză de vaci",
        "Cow Telemea" to "Telemea de vacă",
        "Burduf Cheese" to "Brânză de Burduf",
        "Smoked Burduf Cheese" to "Brânză de Burduf (afumată)",
        "Secărcău Cheese" to "Brânză de Secărcău",
        "Năsal Cheese" to "Brânză de Năsal",
        "Coțofen Cheese" to "Brânză de Coțofen",
        "Măgura Cheese" to "Brânză de Măgura",
        "Cărbune Cheese" to "Brânză de Cărbune",
        "Sour Cream" to "Smântână",
        "Butter" to "Unt",
        "Egg" to "Ou",
        "Kefir / Buttermilk" to "Kefir / Lapte bătut",
        "Skimmed Milk Powder" to "Lapte praf degresat",
        "Meat (Pork, Beef, Poultry)" to "Carne (Porc, Vită, Pasăre)",
        "Fish" to "Pește",
        "Salami" to "Salam",
        "Frankfurter" to "Crenvurst",
        "Liver Pate" to "Pate de ficat",
        "Sugar" to "Zahăr",
        "Powdered Sugar" to "Zahăr pudră",
        "Brown Sugar" to "Zahăr brun",
        "Fructose" to "Fructoză",
        "Glucose" to "Glucoză",
        "Honey" to "Miere",
        "Maple Syrup" to "Sirop de arțar",
        "Milk Chocolate" to "Ciocolată cu lapte",
        "Dark Chocolate (70% Cocoa)" to "Ciocolată neagră (70% cacao)",
        "Plain Biscuit" to "Biscuit simplu",
        "Digestive Biscuit" to "Biscuit digestiv",
        "Chocolate Biscuit" to "Biscuit cu ciocolată",
        "Oat Biscuit" to "Biscuit cu ovăz",
        "Ice Cream" to "Înghețată",
        "Chocolate Wafer" to "Napolitană cu ciocolată",
        "Salted Popcorn" to "Popcorn sărat",
        "Potato Chips" to "Chips",
        "Corn Puff" to "Pufuleț",
        "Walnut / Hazelnut / Almond" to "Nuci / Alune / Migdale",
        "Chia Seeds" to "Semințe de chia",
        "Plain Crepe" to "Clătită simplă",
        "Fruit Compote" to "Compot de fructe",
        "Strawberry Jam" to "Gem de căpșuni",
        "Plain Breadstick" to "Grisină simplă",
        "Cashews" to "Caju",
        "Cheese Pie" to "Plăcintă cu brânză",
        "Apple Pie" to "Plăcintă cu mere",
        "Dobrogean Pie" to "Plăcintă dobrogeană",
        "Sweet Bread Loaf" to "Cozonac",
        "Loaf Cake" to "Chec",
        "Margherita Pizza" to "Pizza Margherita",
        "Pizza (average)" to "Pizza (valoare medie)",
        "Ham and Cheese Pizza" to "Pizza cu șuncă și brânză",
        "Hamburger" to "Hamburger",
        "Sandwich" to "Sandwich",
        "Cabbage Roll with Lamb and Rice" to "Sarma cu miel și orez",
        "Vegetable Soup" to "Ciorbă de legume",
        "Tripe Soup" to "Ciorbă de burtă",
        "Borscht" to "Borș",
        "Meatball Soup" to "Ciorbă de perișoare",
        "Chicken and Vegetable Soup" to "Supă de pui cu legume",
        "Seafood Sushi" to "Sushi cu fructe de mare",
        "Hummus" to "Hummus",
        "Eggplant Salad" to "Salată de vinete",
        "Fish Zacusca" to "Zacuscă de pește",
        "Vegetable Zacusca" to "Zacuscă de legume",
        "Potato Stew" to "Mâncare de cartofi",
        "Vegetable Stew" to "Ghiveci",
        "Moussaka" to "Musaca",
        "Bean Soup" to "Ciorbă de fasole",
        "Bean Stew" to "Iahnie de fasole",
        "Polenta with Cheese" to "Mămăligă cu brânză",
        "Beef Meatball (cooked)" to "Chiftea de vită (gătită)",
        "Romanian Meat Patty" to "Pârjoală",
        "Ostropel" to "Ostropel",
        "Romanian Meat Stew" to "Tochitură",
        "Chicken Schnitzel" to "Șnițel de pui",
        "Soft Drink" to "Suc carbogazos",
        "Fruit Juice" to "Suc de fructe",
        "Beer" to "Bere",
        "Wine" to "Vin",
        "Coffee / Tea (unsweetened)" to "Cafea / Ceai (fără zahăr)",
        "Cappuccino" to "Cappuccino",
        "Latte Macchiato" to "Latte macchiato",
        "Sourdough Bread" to "Pâine cu maia",
        "Gluten-Free White Bread" to "Pâine albă fără gluten",
        "Wheat Tortilla" to "Tortilla de grâu",
        "Corn Tortilla" to "Tortilla de porumb",
        "Basmati Rice (cooked)" to "Orez basmati (fiert)",
        "Basmati Rice (raw)" to "Orez basmati (crud)",
        "Wild Rice (cooked)" to "Orez sălbatic (fiert)",
        "Bulgur (cooked)" to "Bulgur (fiert)",
        "Bulgur (dry)" to "Bulgur (uscat)",
        "Pearl Barley (cooked)" to "Orz perlat (fiert)",
        "Oatmeal (cooked with water)" to "Ovăz (fiert, cu apă)",
        "Whole-Wheat Pasta (cooked)" to "Paste integrale (fierte)",
        "Whole-Wheat Pasta (dry)" to "Paste integrale (crude)",
        "Red Kidney Beans (cooked)" to "Fasole roșie (fiartă)",
        "White Beans (cooked)" to "Fasole albă (fiartă)",
        "Black Beans (cooked)" to "Fasole neagră (fiartă)",
        "Edamame (cooked)" to "Edamame (fiert)",
        "Plain Tofu" to "Tofu simplu",
        "Tempeh" to "Tempeh",
        "Radish" to "Ridiche",
        "Lettuce" to "Salată verde",
        "Arugula" to "Rucola",
        "Asparagus" to "Sparanghel",
        "Green Beans (cooked)" to "Fasole verde (fiartă)",
        "Eggplant (baked)" to "Vânătă (coaptă)",
        "Sweet Potato (baked)" to "Cartofi dulci (copți)",
        "Apple (baked)" to "Măr (copt)",
        "Sweet Cherry" to "Cireșe",
        "Sour Cherry" to "Vișine",
        "Prune" to "Prune uscate",
        "Pomegranate Seeds" to "Rodie (semințe)",
        "Mozzarella Cheese" to "Brânză mozzarella",
        "Feta Cheese" to "Brânză feta",
        "Parmesan" to "Parmezan",
        "Cream Cheese" to "Brânză tartinabilă",
        "Reduced-Lactose Milk" to "Lapte cu lactoză redusă",
        "Oat Milk (unsweetened)" to "Lapte de ovăz (neîndulcit)",
        "Almond Milk (unsweetened)" to "Lapte de migdale (neîndulcit)",
        "Soy Milk (unsweetened)" to "Lapte de soia (neîndulcit)",
        "Plain Lactose-Free Yogurt" to "Iaurt natural (fără lactoză)",
        "Chicken Breast (grilled)" to "Piept de pui (fript)",
        "Turkey (roasted)" to "Carne de curcan (friptă)",
        "Beef (grilled)" to "Carne de vită (friptă)",
        "Pork (cooked)" to "Carne de porc (gătită)",
        "Salmon (cooked)" to "Somon (gătit)",
        "Tuna (canned in water)" to "Ton (conservă, în apă)",
        "Shrimp (boiled)" to "Crevete (fiert)",
        "Walnut" to "Nuci",
        "Almond" to "Migdale",
        "Hazelnut" to "Alune de pădure",
        "Peanuts" to "Arahide",
        "Peanut Butter" to "Unt de arahide",
        "Sunflower Seeds (roasted, salted)" to "Semințe de floarea-soarelui (prăjite, sărate)",
        "Pumpkin Seeds" to "Semințe de dovleac",
        "Olive Oil" to "Ulei de măsline",
        "Sunflower Oil" to "Ulei de floarea-soarelui",
        "Mayonnaise" to "Maioneză",
        "Ketchup" to "Ketchup",
        "Mustard" to "Muștar",
        "White Chocolate" to "Ciocolată albă",
        "Cocoa Powder (unsweetened)" to "Cacao pudră (neîndulcită)",
        "Plain Croissant" to "Croissant simplu",
        "Doughnut" to "Gogoașă",
        "Fruit Mousse Cake" to "Tort cu mousse de fructe",
        "Cheesecake" to "Cheesecake",
        "Vanilla Custard" to "Budincă de vanilie",
        "Granola with Nuts and Seeds" to "Granola cu nuci și semințe",
        "Muesli" to "Musli",
        "Fruit Cereal Bar" to "Baton de cereale cu fructe",
        "Mini Salted Pretzel" to "Covrig sărat (mini)",
        "Chicken Wrap" to "Wrap cu pui",
        "Kebab in Flatbread" to "Kebab în lipie",
        "Meat Lasagna" to "Lasagna cu carne",
        "Vegetable Risotto" to "Risotto cu legume",
        "Cream of Vegetable Soup" to "Supă cremă de legume",
        "Boeuf Salad" to "Salată de boeuf",
        "Fresh Fruit Salad" to "Salată de fructe (proaspete)",
        "Water" to "Apă",
        "Mineral Water" to "Apă minerală",
        "Orange Juice" to "Suc de portocale",
        "Apple Juice" to "Suc de mere",
        "Lemonade (sweetened)" to "Limonadă (cu zahăr)",
        "Sugar-Free Soft Drink" to "Băutură carbogazoasă fără zahăr",
        "Energy Drink" to "Băutură energizantă",
        "Black Coffee" to "Cafea neagră",
        "Coffee with Milk (unsweetened)" to "Cafea cu lapte (fără zahăr)",
        "Tea (unsweetened)" to "Ceai (fără zahăr)",
        "Sweetened Iced Tea" to "Ceai rece îndulcit",
        "Hot Chocolate" to "Ciocolată caldă",
        "Alcohol-Free Beer" to "Bere fără alcool",
        "Cider" to "Cidru",
        "Dry Wine" to "Vin sec",
        "Sweet Wine" to "Vin dulce",
        "Naan Bread" to "Pâine naan",
        "Chapati" to "Pâine chapati",
        "Egg Noodles (cooked)" to "Tăiței cu ou (fierți)",
        "Rice Noodles (cooked)" to "Tăiței de orez (fierți)",
        "Adzuki Beans (cooked)" to "Fasole adzuki (fiartă)",
        "Mung Beans (cooked)" to "Fasole mung (fiartă)",
        "Artichoke (boiled)" to "Anghinare (fiartă)",
        "Kale (raw)" to "Varză kale (crudă)",
        "Kale (boiled)" to "Varză kale (fiartă)",
        "Guava" to "Guava",
        "Coconut (fresh)" to "Nucă de cocos (proaspătă)",
        "Lamb (roasted)" to "Carne de miel (friptă)",
        "Duck (roasted)" to "Carne de rață (friptă)",
        "Cheddar Cheese" to "Brânză cheddar",
        "Falafel" to "Falafel",
        "Guacamole" to "Guacamole",
        "Chili con Carne" to "Chili con carne",
        "Beef Burrito" to "Burrito cu vită",
        "Potato Gnocchi (cooked)" to "Gnocchi de cartofi (fierți)",
        "Pasta Carbonara" to "Paste carbonara",
        "Pasta Bolognese" to "Paste bolognese",
        "Steamed Shrimp Dumpling" to "Colțunaș cu creveți (la abur)",
        "Spring Roll" to "Pachețel de primăvară",
        "Samosa" to "Samosa",
        "Chicken Biryani" to "Biryani cu pui",
        "Chicken Tikka Masala" to "Pui tikka masala",
        "Chicken Korma" to "Pui korma",
        "Lentil Curry" to "Curry de linte",
        "Couscous with Vegetables" to "Cuscus cu legume",
        "Tabbouleh" to "Tabbouleh",
        "Tzatziki" to "Tzatziki",
        "Baklava" to "Baklava",
        "Minestrone Soup" to "Supă minestrone",
        "Miso Soup" to "Supă miso",
        "Ratatouille" to "Ratatouille",
        "Salmon Nigiri Sushi" to "Sushi nigiri cu somon",
        "Vegetarian Sushi" to "Sushi vegetarian",
        "Greek Salad" to "Salată grecească",
        "Plantain (raw)" to "Banană plantain (crudă)",
        "Nectarine" to "Nectarină",
        "Lime" to "Lime",
        "Fresh Date" to "Curmale proaspete",
        "Pickled Beetroot" to "Sfeclă roșie murată",
        "Pinto Beans (cooked)" to "Fasole pinto (fiartă)",
        "Lychee" to "Litchi",
        "Cola with Sugar" to "Cola cu zahăr",
        "Sugar-Free Cola" to "Cola fără zahăr",
        "Grapefruit Juice" to "Suc de grapefruit",
        "Green Tea (unsweetened)" to "Ceai verde (fără zahăr)",
        "Espresso (unsweetened)" to "Cafea espresso (fără zahăr)"
    )

    private val previousRomanianToEnglish = mapOf(
        "Ciupercă" to "Mushroom",
        "Ciupercă Champignon (crudă)" to "Button Mushroom (raw)",
        "Ciupercă (conservă)" to "Mushroom (canned)",
        "Ciupercă murată" to "Pickled Mushroom",
        "Măslină (verde/neagră)" to "Olive (green/black)",
        "Măslină uscată" to "Dried Olive",
        "Caisă uscată" to "Dried Apricot",
        "Nucă / Alună / Migdală" to "Walnut / Hazelnut / Almond",
        "Prună uscată" to "Prune",
        "Nucă" to "Walnut",
        "Migdală" to "Almond",
        "Alună de pădure" to "Hazelnut",
        "Cartof (fiert)" to "Potato (boiled)",
        "Cartof (prăjit acasă)" to "French Fries (home-cooked)",
        "Cartofi (prăjiți acasă)" to "French Fries (home-cooked)",
        "Cartof pai (fast-food)" to "French Fries (fast food)",
        "Cartof (copt)" to "Potato (baked)",
        "Piure de cartof" to "Mashed Potato",
        "Cartof dulce" to "Sweet Potato",
        "Cartof (crud)" to "Potato (raw)",
        "Cartof dulce (crud)" to "Sweet Potato (raw)",
        "Căpșună" to "Strawberry",
        "Căpșună (conservă)" to "Strawberry (canned)",
        "Afină" to "Blueberry",
        "Curmală / Smochină (uscată)" to "Dried Date / Fig",
        "Curmală uscată" to "Dried Date",
        "Smochină uscată" to "Dried Fig",
        "Stafidă" to "Raisin",
        "Mură" to "Blackberry",
        "Coacăză neagră" to "Blackcurrant",
        "Coacăză roșie" to "Redcurrant",
        "Coacăză albă" to "White Currant",
        "Măceașă" to "Rose Hip",
        "Cartof dulce (copt)" to "Sweet Potato (baked)",
        "Cireașă" to "Sweet Cherry",
        "Vișină" to "Sour Cherry",
        "Gnocchi de cartof (fierți)" to "Potato Gnocchi (cooked)",
        "Curmală proaspătă" to "Fresh Date"
    )

    private val romanianToEnglish = englishToRomanian.entries.associate { (english, romanian) ->
        romanian to english
    }

    fun romanianName(englishName: String): String? = englishToRomanian[
        if (englishName == "Potato (home-fried)") "French Fries (home-cooked)" else englishName
    ]

    fun englishName(romanianName: String): String? = romanianToEnglish[romanianName] ?: previousRomanianToEnglish[romanianName]
}
