package com.glicocalc.database

data class InitialFood(val name: String, val carbs: Double)

object InitialData {
    val foods = listOf(
        InitialFood("Pâine Albă", 49.0),
        InitialFood("Pâine Integrală", 41.0),
        InitialFood("Pâine de Secară", 45.0),
        InitialFood("Pâine cu Semințe", 43.0),
        InitialFood("Pâine Toast", 52.0),
        InitialFood("Baghetă Franceză", 47.0),
        InitialFood("Covrig", 55.0),
        InitialFood("Chifle", 48.0),
        InitialFood("Orez Alb (fiert)", 28.0),
        InitialFood("Orez Brun (fiert)", 23.0),
        InitialFood("Paste Făinoase (fierte)", 25.0),
        InitialFood("Spaghetti (fiert)", 25.0),
        InitialFood("Mămăligă (vârtoasă)", 15.0),
        InitialFood("Mămăligă (moale)", 20.0),
        InitialFood("Fulgi de Ovăz", 60.0),
        InitialFood("Griș", 72.0),
        InitialFood("Cuscus (fiert)", 23.0),
        InitialFood("Quinoa (fiert)", 21.0),
        InitialFood("Hrișcă (fiertă)", 19.0),
        InitialFood("Mazăre", 14.0),
        InitialFood("Linte (fiartă)", 20.0),
        InitialFood("Năut (fiert)", 27.0),
        InitialFood("Fasole Boabe (fiartă)", 15.0),
        InitialFood("Fasole Păstăi", 5.0),
        InitialFood("Soia (fiartă)", 9.0),
        InitialFood("Cartofi Fierți", 17.0),
        InitialFood("Cartofi Prăjiți", 35.0),
        InitialFood("Piure de Cartofi", 14.0),
        InitialFood("Cartofi Copți", 21.0),
        InitialFood("Cartofi Dulce", 20.0),
        InitialFood("Sfeclă Roșie", 10.0),
        InitialFood("Morcov", 7.0),
        InitialFood("Morcov (fiert)", 8.0),
        InitialFood("Pastinac", 10.0),
        InitialFood("Țelină", 6.0),
        InitialFood("Rădăcină de Pătrunjel", 10.0),
        InitialFood("Porumb (conservă)", 18.0),
        InitialFood("Porumb fiert", 17.0),
        InitialFood("Broccoli", 4.0),
        InitialFood("Broccoli (fiert)", 5.0),
        InitialFood("Conopidă", 4.0),
        InitialFood("Conopidă (prăjită)", 5.0),
        InitialFood("Varză", 4.0),
        InitialFood("Varză (fiartă)", 5.0),
        InitialFood("Varză Roșie", 5.0),
        InitialFood("Varză de Bruxelles", 6.0),
        InitialFood("Gulii", 5.0),
        InitialFood("Salată Verde", 2.0),
        InitialFood("Roșii", 3.0),
        InitialFood("Roșii Cherry", 4.0),
        InitialFood("Roșii (conservă)", 4.0),
        InitialFood("Castraveți", 2.0),
        InitialFood("Castraveți Murați", 2.0),
        InitialFood("Dovlecei", 3.0),
        InitialFood("Dovleac", 6.0),
        InitialFood("Vânăta", 5.0),
        InitialFood("Ardei Gras", 5.0),
        InitialFood("Ardei Iute", 8.0),
        InitialFood("Gogoșari", 6.0),
        InitialFood("Ceapă", 7.0),
        InitialFood("Usturoi", 30.0),
        InitialFood("Praz", 10.0),
        InitialFood("Spanac", 3.0),
        InitialFood("Mangold", 3.0),
        InitialFood("Urinaș", 3.0),
        InitialFood("Lobodă", 4.0),
        InitialFood("Soriz", 5.0),
        InitialFood("Ciuperci", 3.0),
        InitialFood("Ciuperci Champignon", 3.0),
        InitialFood("Ciuperci (conservă)", 4.0),
        InitialFood("Avocado", 9.0),
        InitialFood("Măsline Verzi", 3.0),
        InitialFood("Măsline Negre", 4.0),
        InitialFood("Măsline Uscate", 20.0),
        InitialFood("Ulei de Măsline", 0.0),
        InitialFood("Unt", 0.1),
        InitialFood("Untura de Porc", 0.0),
        InitialFood("Smântână", 3.5),
        InitialFood("Smântână pentru frișcă", 3.0),
        InitialFood("Smântână lichidă", 3.5),
        InitialFood("Mazăre verde", 14.0),
        InitialFood("Fasole verde", 5.0),
        InitialFood("Mărar", 5.0),
        InitialFood("Pătrunjel (frunze)", 6.0),
        InitialFood("Busuioc", 2.0),
        InitialFood("Coriandru", 3.0),
        InitialFood("Leuștean", 7.0),
        InitialFood("Măr", 12.0),
        InitialFood("Măr (cules)", 13.0),
        InitialFood("Măr Golden", 14.0),
        InitialFood("Măr Ionatan", 12.0),
        InitialFood("Măr Idared", 11.0),
        InitialFood("Măr Fuji", 11.0),
        InitialFood("Măr Granny Smith", 10.0),
        InitialFood("Banane", 20.0),
        InitialFood("Banane coapte", 23.0),
        InitialFood("Banane verzi", 15.0),
        InitialFood("Portocală", 9.0),
        InitialFood("Portocală Sanguinello", 10.0),
        InitialFood("Mandarină", 8.0),
        InitialFood("Clementină", 10.0),
        InitialFood("Lămâie", 3.0),
        InitialFood("Lămâie (suc)", 2.0),
        InitialFood("Grepfrut", 6.0),
        InitialFood("Grepfrut roșu", 7.0),
        InitialFood("Pere", 12.0),
        InitialFood("Pere Williams", 11.0),
        InitialFood("Pere Abate", 13.0),
        InitialFood("Pere Kaiser", 11.0),
        InitialFood("Struguri", 18.0),
        InitialFood("Struguri albi", 17.0),
        InitialFood("Struguri negri", 17.0),
        InitialFood("Stafide", 75.0),
        InitialFood("Căpșuni", 7.0),
        InitialFood("Căpșuni (conservă)", 8.0),
        InitialFood("Afine", 14.0),
        InitialFood("Mure", 10.0),
        InitialFood("Zmeură", 10.0),
        InitialFood("Coacăze negre", 15.0),
        InitialFood("Coacăze roșii", 12.0),
        InitialFood("Coacăze albe", 13.0),
        InitialFood("Căpsină", 7.0),
        InitialFood("Lonicera", 12.0),
        InitialFood("Măceșe", 25.0),
        InitialFood("Piersici", 9.0),
        InitialFood("Nectarine", 10.0),
        InitialFood("Caise", 9.0),
        InitialFood("Caise uscate", 62.0),
        InitialFood("Piersici uscate", 65.0),
        InitialFood("Prune", 10.0),
        InitialFood("Prune uscate (prune)", 64.0),
        InitialFood("Pepene Roșu", 7.0),
        InitialFood("Pepene Galben", 8.0),
        InitialFood("Rodie", 14.0),
        InitialFood("Strudel", 50.0),
        InitialFood("Kiwi", 12.0),
        InitialFood("Ananas", 12.0),
        InitialFood("Mango", 14.0),
        InitialFood("Papaya", 10.0),
        InitialFood("Fructul Passion", 13.0),
        InitialFood("Curmale", 66.0),
        InitialFood("Curmale uscate", 75.0),
        InitialFood("Smochine", 12.0),
        InitialFood("Smochine uscate", 60.0),
        InitialFood("Smochine proaspete", 12.0),
        InitialFood("Smochine verzi", 10.0),
        InitialFood("Nucă", 15.0),
        InitialFood("Alune", 15.0),
        InitialFood("Fistic", 20.0),
        InitialFood("Migdale", 20.0),
        InitialFood("Caju", 30.0),
        InitialFood("Făină de Grâu", 72.0),
        InitialFood("Făină Integrală", 65.0),
        InitialFood("Făină de Porumb", 75.0),
        InitialFood("Făină de Orez", 78.0),
        InitialFood("Făină de Secară", 72.0),
        InitialFood("Făină de Mei", 75.0),
        InitialFood("Amidon de Porumb", 87.0),
        InitialFood("Pesmet", 70.0),
        InitialFood("Pané", 68.0),
        InitialFood("Lapte de Vacă (3.5%)", 4.7),
        InitialFood("Lapte de Vacă (2%)", 5.0),
        InitialFood("Lapte de Vacă degresat", 5.0),
        InitialFood("Lapte de Capră", 4.5),
        InitialFood("Lapte de oaie", 5.0),
        InitialFood("Lapte condensat", 12.0),
        InitialFood("Lapte praf degresat", 52.0),
        InitialFood("Smântână de lapte", 3.5),
        InitialFood("Iaurt Natur", 4.5),
        InitialFood("Iaurt Grecesc", 4.0),
        InitialFood("Iaurt cu Fructe", 12.0),
        InitialFood("Iaurt de băut", 11.0),
        InitialFood("Kefir", 4.5),
        InitialFood("Lapte bătut", 4.5),
        InitialFood("Brânză de Vaci", 4.0),
        InitialFood("Brânză de Vaci slabă", 3.0),
        InitialFood("Brânză de Burduf", 1.5),
        InitialFood("Brânză de Burduf (afumată)", 1.0),
        InitialFood("Brânză de Secărcău", 1.5),
        InitialFood("Brânză de Năsal", 2.0),
        InitialFood("Brânză de Coțofen", 1.5),
        InitialFood("Brânză de Măgura", 1.8),
        InitialFood("Brânză de Cărbune", 2.0),
        InitialFood("Telemea de vacă", 1.5),
        InitialFood("Telemea de oaie", 2.0),
        InitialFood("Cașcaval", 1.0),
        InitialFood("Cașcaval afumat", 1.2),
        InitialFood("Emmental", 1.0),
        InitialFood("Gouda", 1.5),
        InitialFood("Edam", 1.5),
        InitialFood("Tilsiter", 1.5),
        InitialFood("Brie", 0.5),
        InitialFood("Camembert", 0.5),
        InitialFood("Roquefort", 0.5),
        InitialFood("Gorgonzola", 0.5),
        InitialFood("Mozzarella", 1.0),
        InitialFood("Mozzarella de bivol", 1.0),
        InitialFood("Parmezan", 1.0),
        InitialFood("Pecorino", 1.5),
        InitialFood("Ricotta", 3.0),
        InitialFood("Mascarpone", 4.0),
        InitialFood("Cottage Cheese", 3.0),
        InitialFood("Cream Cheese", 4.0),
        InitialFood("Schmand", 4.0),
        InitialFood("Smântână acră", 3.5),
        InitialFood("Frișcă", 3.0),
        InitialFood("Frișcă vegetală", 3.5),
        InitialFood("Ou de găină", 0.7),
        InitialFood("Ou de rață", 1.0),
        InitialFood("Ou de gâscă", 1.3),
        InitialFood("Ou de prepeliță", 0.4),
        InitialFood("Ou fiert", 0.8),
        InitialFood("Ou prăjit", 1.0),
        InitialFood("Omuletă", 1.0),
        InitialFood("Carne de Pui", 0.0),
        InitialFood("Piept de Pui", 0.0),
        InitialFood("Pulpe de Pui", 0.0),
        InitialFood("Carne de Curcan", 0.0),
        InitialFood("Carne de Rață", 0.0),
        InitialFood("Carne de Găină", 0.0),
        InitialFood("Carne de Porc", 0.0),
        InitialFood("Carne de Porc slabă", 0.0),
        InitialFood("Carne de Vițel", 0.0),
        InitialFood("Carne de Vită", 0.0),
        InitialFood("Carne de Bovina", 0.0),
        InitialFood("Carne de Mânz", 0.0),
        InitialFood("Carne de Oaie", 0.0),
        InitialFood("Carne de Iepure", 0.0),
        InitialFood("Carne de Vânat", 0.0),
        InitialFood("Carne de Mistreț", 0.0),
        InitialFood("Carne de Căprior", 0.0),
        InitialFood("Icre de pește", 1.5),
        InitialFood("Icre de Manț", 1.0),
        InitialFood("Icre de hering", 1.0),
        InitialFood("Icre negre", 3.0),
        InitialFood("Sardine", 0.0),
        InitialFood("Somon", 0.0),
        InitialFood("Macrou", 0.0),
        InitialFood("Hering", 0.0),
        InitialFood("Cod", 0.0),
        InitialFood("Stimpan", 0.0),
        InitialFood("Știucă", 0.0),
        InitialFood("Caras", 0.0),
        InitialFood("Crap", 0.0),
        InitialFood("Lin", 0.0),
        InitialFood("Somn", 0.0),
        InitialFood("Biban", 0.0),
        InitialFood("Păstrăv", 0.0),
        InitialFood("Cocktail de fructe", 15.0),
        InitialFood("Compot de fructe", 18.0),
        InitialFood("Gem de fructe", 65.0),
        InitialFood("Dulceață de fructe", 70.0),
        InitialFood("Marmeladă", 72.0),
        InitialFood("Sirop de fructe", 75.0),
        InitialFood("Zahăr", 100.0),
        InitialFood("Zahăr pudră", 100.0),
        InitialFood("Zahăr brun", 98.0),
        InitialFood("Fructoză", 100.0),
        InitialFood("Glucoză", 100.0),
        InitialFood("Miere", 80.0),
        InitialFood("Miere de salcâm", 82.0),
        InitialFood("Miere de tei", 81.0),
        InitialFood("Miere de polifloră", 80.0),
        InitialFood("Sirop de arțar", 60.0),
        InitialFood("Melasă", 55.0),
        InitialFood("Biscuiți", 70.0),
        InitialFood("Biscuiți Populari", 75.0),
        InitialFood("Biscuiți cu ciocolată", 65.0),
        InitialFood("Biscuiți digestive", 68.0),
        InitialFood("Gașcă", 75.0),
        InitialFood("Covrigi cu mac", 60.0),
        InitialFood("Covrigi simpli", 55.0),
        InitialFood("Lipie", 50.0),
        InitialFood("Pită", 48.0),
        InitialFood("Plăcintă cu brânză", 30.0),
        InitialFood("Plăcintă cu mere", 35.0),
        InitialFood("Plăcintădobrogeană", 28.0),
        InitialFood("Sarmale", 8.0),
        InitialFood("Mâncare de cartofi", 15.0),
        InitialFood("Ciorbă de burtă", 5.0),
        InitialFood("Ciorbă de fasole", 12.0),
        InitialFood("Ciorbă de legume", 6.0),
        InitialFood("Supă de pui", 3.0),
        InitialFood("Supă de legume", 5.0),
        InitialFood("Bors", 4.0),
        InitialFood("Ciorbă de perisoare", 5.0),
        InitialFood("Zacusca de pește", 4.0),
        InitialFood("Zacusca de legume", 8.0),
        InitialFood("Leustean cu smantana", 5.0),
        InitialFood("Mamaliga cu branza", 12.0),
        InitialFood("Mamaliga cu lapte", 15.0),
        InitialFood("Jumări", 1.0),
        InitialFood("Slănină", 0.0),
        InitialFood("Cârnați", 1.0),
        InitialFood("Cârnați de Pleșcaiu", 1.5),
        InitialFood("Mititei", 2.0),
        InitialFood("Hamburger", 25.0),
        InitialFood("Hot Dog", 28.0),
        InitialFood("Shaorma", 25.0),
        InitialFood("Döner Kebab", 20.0),
        InitialFood("Pizza Margherita", 32.0),
        InitialFood("Pizza cu pepperoni", 35.0),
        InitialFood("Sandwich", 35.0),
        InitialFood("Clătite", 40.0),
        InitialFood("Clătite cu brânză", 35.0),
        InitialFood("Gogoși", 45.0),
        InitialFood("Cozonac", 50.0),
        InitialFood("Chec", 45.0),
        InitialFood("Prajitură cu ciocolată", 50.0),
        InitialFood("Ecler", 40.0),
        InitialFood("Amandine", 55.0),
        InitialFood("Ruladă", 45.0),
        InitialFood("Tort", 55.0),
        InitialFood("Salată de vinete", 7.0),
        InitialFood("Salată de gud Strela", 8.0),
        InitialFood("Ic", 10.0),
        InitialFood("Salată de ardei copți", 9.0),
        InitialFood("Tzatziki", 4.0),
        InitialFood("Hummus", 15.0),
        InitialFood("Varză acră", 3.0),
        InitialFood("Murături", 2.0),
        InitialFood("Castraveți murați", 2.0),
        InitialFood("Gogonele", 4.0),
        InitialFood("Ardei iuți murați", 5.0),
        InitialFood("Ciuperci murate", 4.0),
        InitialFood("Măsline murate", 4.0),
        InitialFood("Ghiveci", 12.0),
        InitialFood("Varză călită", 10.0),
        InitialFood("Cartofi călită", 15.0),
        InitialFood("Cartofi la cuptor", 18.0),
        InitialFood("Cartofi gratinați", 16.0),
        InitialFood("Legume la grătar", 8.0),
        InitialFood("Legume fierte", 6.0),
        InitialFood("Legume înăbușite", 10.0),
        InitialFood("Batog de pește", 0.0),
        InitialFood("File de pește", 0.0),
        InitialFood("Pate de ficat", 5.0),
        InitialFood("Crudități", 8.0),
        InitialFood("Aspic", 2.0),
        InitialFood("Ruladă de curcan", 2.0),
        InitialFood("Ruladă de pui", 2.0),
        InitialFood("Chiftele", 8.0),
        InitialFood("Parjoale", 10.0),
        InitialFood("Snitel de pui", 8.0),
        InitialFood("Snitel de porc", 7.0),
        InitialFood("Cotlet de porc", 0.0),
        InitialFood("Antricot", 0.0),
        InitialFood("Mușchi de porc", 0.0),
        InitialFood("Mușchi de vacă", 0.0),
        InitialFood("Coaste de porc", 0.0),
        InitialFood("Ceafă de porc", 0.0),
        InitialFood("Schnitzel", 8.0),
        InitialFood("Cartofi pai", 30.0),
        InitialFood("Ostropel", 6.0),
        InitialFood("Musaca", 18.0),
        InitialFood("Tochitura", 8.0),
        InitialFood("Mici", 3.0),
        InitialFood("Crenvurști", 15.0),
        InitialFood("Bacon", 1.0),
        InitialFood("Șuncă", 1.5),
        InitialFood("Prosciutto", 0.5),
        InitialFood("Salam", 2.0),
        InitialFood("Salam de Sibiu", 2.5),
        InitialFood("Salam de Timișoara", 2.0),
        InitialFood("Pastramă", 1.5),
        InitialFood("Carne uscată", 1.0),
        InitialFood("Ceai negru", 0.0),
        InitialFood("Ceai verde", 0.0),
        InitialFood("Ceai de mușețel", 0.5),
        InitialFood("Cafea", 0.0),
        InitialFood("Cafea cu lapte", 1.5),
        InitialFood("Cappuccino", 2.0),
        InitialFood("Latte macchiato", 2.5),
        InitialFood("Espresso", 0.0),
        InitialFood("Răcoritoare", 11.0),
        InitialFood("Coca Cola", 10.6),
        InitialFood("Fanta", 11.0),
        InitialFood("Sprite", 10.0),
        InitialFood("Pepsi", 10.0),
        InitialFood("Suc de portocale", 10.0),
        InitialFood("Suc de mere", 11.0),
        InitialFood("Suc de struguri", 16.0),
        InitialFood("Suc de roșii", 4.0),
        InitialFood("Suc de grepfrut", 9.0),
        InitialFood("Nectar de piersici", 12.0),
        InitialFood("Nectar de caise", 14.0),
        InitialFood("Bere", 4.5),
        InitialFood("Bere blondă", 4.8),
        InitialFood("Bere neagră", 5.0),
        InitialFood("Vin roșu", 2.0),
        InitialFood("Vin alb", 2.5),
        InitialFood("Vin rose", 3.0),
        InitialFood("Vin spumant", 4.0),
        InitialFood("Tuica", 0.0),
        InitialFood("Palinca", 0.0),
        InitialFood("Rachiu", 0.0),
        InitialFood("Coniac", 0.0),
        InitialFood("Vodka", 0.0),
        InitialFood("Whiskey", 0.0),
        InitialFood("Bautura energizanta", 11.0),
        InitialFood("Isostar", 8.0),
        InitialFood("Gatorade", 6.0),
        InitialFood("Apa", 0.0),
        InitialFood("Apa minerala", 0.0)
    )
}