package com.glicocalc.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import com.glicocalc.logic.removeDiacritics

@Composable
fun rememberBaseFoodNameResolver(): (String) -> String {
    val currentLocale = LocalAppLocale.current
    val languageCode = remember(currentLocale) { currentLocale.lowercase() }
    return remember(languageCode) {
        if (languageCode.startsWith("ro")) {
            { name -> name }
        } else {
            { name -> englishBaseFoodNames[name] ?: name }
        }
    }
}

fun matchesBaseFoodQuery(
    rawName: String,
    localizedName: String,
    query: String
): Boolean {
    val normalizedQuery = query.removeDiacritics()
    return rawName.removeDiacritics().contains(normalizedQuery, ignoreCase = true) ||
        localizedName.removeDiacritics().contains(normalizedQuery, ignoreCase = true)
}

private val englishBaseFoodNames = mapOf(
    "Pâine Albă" to "White Bread",
    "Pâine Integrală" to "Whole Wheat Bread",
    "Pâine de Secară" to "Rye Bread",
    "Pâine cu Semințe" to "Seeded Bread",
    "Pâine Toast" to "Toast Bread",
    "Baghetă Franceză" to "French Baguette",
    "Covrig" to "Pretzel",
    "Chifle" to "Bread Rolls",
    "Orez Alb (fiert)" to "White Rice (boiled)",
    "Orez Brun (fiert)" to "Brown Rice (boiled)",
    "Paste Făinoase (fierte)" to "Pasta (boiled)",
    "Spaghetti (fiert)" to "Spaghetti (boiled)",
    "Mămăligă (vârtoasă)" to "Polenta (firm)",
    "Mămăligă (moale)" to "Polenta (soft)",
    "Fulgi de Ovăz" to "Oat Flakes",
    "Griș" to "Semolina",
    "Cuscus (fiert)" to "Couscous (boiled)",
    "Quinoa (fiert)" to "Quinoa (boiled)",
    "Hrișcă (fiertă)" to "Buckwheat (boiled)",
    "Mazăre" to "Peas",
    "Linte (fiartă)" to "Lentils (boiled)",
    "Năut (fiert)" to "Chickpeas (boiled)",
    "Fasole Boabe (fiartă)" to "Beans (boiled)",
    "Fasole Păstăi" to "Green Beans",
    "Soia (fiartă)" to "Soybeans (boiled)",
    "Cartofi Fierți" to "Boiled Potatoes",
    "Cartofi Prăjiți" to "French Fries",
    "Piure de Cartofi" to "Mashed Potatoes",
    "Cartofi Copți" to "Baked Potatoes",
    "Cartofi Dulce" to "Sweet Potato",
    "Sfeclă Roșie" to "Beetroot",
    "Morcov" to "Carrot",
    "Morcov (fiert)" to "Carrot (boiled)",
    "Pastinac" to "Parsnip",
    "Țelină" to "Celery Root",
    "Rădăcină de Pătrunjel" to "Parsley Root",
    "Porumb (conservă)" to "Corn (canned)",
    "Porumb fiert" to "Corn (boiled)",
    "Broccoli" to "Broccoli",
    "Broccoli (fiert)" to "Broccoli (boiled)",
    "Conopidă" to "Cauliflower",
    "Conopidă (prăjită)" to "Cauliflower (fried)",
    "Varză" to "Cabbage",
    "Varză (fiartă)" to "Cabbage (boiled)",
    "Varză Roșie" to "Red Cabbage",
    "Varză de Bruxelles" to "Brussels Sprouts",
    "Gulii" to "Kohlrabi",
    "Salată Verde" to "Lettuce",
    "Roșii" to "Tomatoes",
    "Roșii Cherry" to "Cherry Tomatoes",
    "Roșii (conservă)" to "Tomatoes (canned)",
    "Castraveți" to "Cucumbers",
    "Castraveți Murați" to "Pickled Cucumbers",
    "Dovlecei" to "Zucchini",
    "Dovleac" to "Pumpkin",
    "Vânăta" to "Eggplant",
    "Ardei Gras" to "Bell Pepper",
    "Ardei Iute" to "Hot Pepper",
    "Gogoșari" to "Red Bell Pepper",
    "Ceapă" to "Onion",
    "Usturoi" to "Garlic",
    "Praz" to "Leek",
    "Spanac" to "Spinach",
    "Mangold" to "Chard",
    "Urinaș" to "Urinaș",
    "Lobodă" to "Orache",
    "Soriz" to "Soriz",
    "Ciuperci" to "Mushrooms",
    "Ciuperci Champignon" to "Button Mushrooms",
    "Ciuperci (conservă)" to "Mushrooms (canned)",
    "Avocado" to "Avocado",
    "Măsline Verzi" to "Green Olives",
    "Măsline Negre" to "Black Olives",
    "Măsline Uscate" to "Dried Olives",
    "Ulei de Măsline" to "Olive Oil",
    "Unt" to "Butter",
    "Untura de Porc" to "Lard",
    "Smântână" to "Sour Cream",
    "Smântână pentru frișcă" to "Whipping Cream",
    "Smântână lichidă" to "Liquid Cream",
    "Mazăre verde" to "Green Peas",
    "Fasole verde" to "Green Beans",
    "Mărar" to "Dill",
    "Pătrunjel (frunze)" to "Parsley (leaves)",
    "Busuioc" to "Basil",
    "Coriandru" to "Coriander",
    "Leuștean" to "Lovage",
    "Măr" to "Apple",
    "Măr (cules)" to "Freshly Picked Apple",
    "Măr Golden" to "Golden Apple",
    "Măr Ionatan" to "Jonathan Apple",
    "Măr Idared" to "Idared Apple",
    "Măr Fuji" to "Fuji Apple",
    "Măr Granny Smith" to "Granny Smith Apple",
    "Banane" to "Bananas",
    "Banane coapte" to "Ripe Bananas",
    "Banane verzi" to "Green Bananas",
    "Portocală" to "Orange",
    "Portocală Sanguinello" to "Blood Orange",
    "Mandarină" to "Mandarin",
    "Clementină" to "Clementine",
    "Lămâie" to "Lemon",
    "Lămâie (suc)" to "Lemon Juice",
    "Grepfrut" to "Grapefruit",
    "Grepfrut roșu" to "Red Grapefruit",
    "Pere" to "Pears",
    "Pere Williams" to "Williams Pear",
    "Pere Abate" to "Abate Pear",
    "Pere Kaiser" to "Kaiser Pear",
    "Struguri" to "Grapes",
    "Struguri albi" to "White Grapes",
    "Struguri negri" to "Black Grapes",
    "Stafide" to "Raisins",
    "Căpșuni" to "Strawberries",
    "Căpșuni (conservă)" to "Strawberries (canned)",
    "Afine" to "Blueberries",
    "Mure" to "Blackberries",
    "Zmeură" to "Raspberries",
    "Coacăze negre" to "Blackcurrants",
    "Coacăze roșii" to "Redcurrants",
    "Coacăze albe" to "White Currants",
    "Căpsină" to "Wild Strawberry",
    "Lonicera" to "Honeysuckle Berry",
    "Măceșe" to "Rose Hips",
    "Piersici" to "Peaches",
    "Nectarine" to "Nectarines",
    "Caise" to "Apricots",
    "Caise uscate" to "Dried Apricots",
    "Piersici uscate" to "Dried Peaches",
    "Prune" to "Plums",
    "Prune uscate (prune)" to "Prunes",
    "Pepene Roșu" to "Watermelon",
    "Pepene Galben" to "Melon",
    "Rodie" to "Pomegranate",
    "Strudel" to "Strudel",
    "Kiwi" to "Kiwi",
    "Ananas" to "Pineapple",
    "Mango" to "Mango",
    "Papaya" to "Papaya",
    "Fructul Passion" to "Passion Fruit",
    "Curmale" to "Dates",
    "Curmale uscate" to "Dried Dates",
    "Smochine" to "Figs",
    "Smochine uscate" to "Dried Figs",
    "Smochine proaspete" to "Fresh Figs",
    "Smochine verzi" to "Green Figs",
    "Nucă" to "Walnut",
    "Alune" to "Hazelnuts",
    "Fistic" to "Pistachios",
    "Migdale" to "Almonds",
    "Caju" to "Cashews",
    "Făină de Grâu" to "Wheat Flour",
    "Făină Integrală" to "Whole Wheat Flour",
    "Făină de Porumb" to "Corn Flour",
    "Făină de Orez" to "Rice Flour",
    "Făină de Secară" to "Rye Flour",
    "Făină de Mei" to "Millet Flour",
    "Amidon de Porumb" to "Corn Starch",
    "Pesmet" to "Breadcrumbs",
    "Pané" to "Breading",
    "Lapte de Vacă (3.5%)" to "Cow's Milk (3.5%)",
    "Lapte de Vacă (2%)" to "Cow's Milk (2%)",
    "Lapte de Vacă degresat" to "Skimmed Cow's Milk",
    "Lapte de Capră" to "Goat Milk",
    "Lapte de oaie" to "Sheep Milk",
    "Lapte condensat" to "Condensed Milk",
    "Lapte praf degresat" to "Skimmed Milk Powder",
    "Smântână de lapte" to "Milk Cream",
    "Iaurt Natur" to "Plain Yogurt",
    "Iaurt Grecesc" to "Greek Yogurt",
    "Iaurt cu Fructe" to "Fruit Yogurt",
    "Iaurt de băut" to "Drinking Yogurt",
    "Kefir" to "Kefir",
    "Lapte bătut" to "Buttermilk",
    "Brânză de Vaci" to "Farmer Cheese",
    "Brânză de Vaci slabă" to "Low-Fat Farmer Cheese",
    "Brânză de Burduf" to "Burduf Cheese",
    "Brânză de Burduf (afumată)" to "Smoked Burduf Cheese",
    "Brânză de Secărcău" to "Secărcău Cheese",
    "Brânză de Năsal" to "Năsal Cheese",
    "Brânză de Coțofen" to "Coțofen Cheese",
    "Brânză de Măgura" to "Măgura Cheese",
    "Brânză de Cărbune" to "Cărbune Cheese",
    "Telemea de vacă" to "Cow Telemea",
    "Telemea de oaie" to "Sheep Telemea",
    "Cașcaval" to "Semi-Hard Cheese",
    "Cașcaval afumat" to "Smoked Semi-Hard Cheese",
    "Emmental" to "Emmental",
    "Gouda" to "Gouda",
    "Edam" to "Edam",
    "Tilsiter" to "Tilsiter",
    "Brie" to "Brie",
    "Camembert" to "Camembert",
    "Roquefort" to "Roquefort",
    "Gorgonzola" to "Gorgonzola",
    "Mozzarella" to "Mozzarella",
    "Mozzarella de bivol" to "Buffalo Mozzarella",
    "Parmezan" to "Parmesan",
    "Pecorino" to "Pecorino",
    "Ricotta" to "Ricotta",
    "Mascarpone" to "Mascarpone",
    "Cottage Cheese" to "Cottage Cheese",
    "Cream Cheese" to "Cream Cheese",
    "Schmand" to "Schmand",
    "Smântână acră" to "Sour Cream",
    "Frișcă" to "Whipped Cream",
    "Frișcă vegetală" to "Vegetable Whipped Cream",
    "Ou de găină" to "Chicken Egg",
    "Ou de rață" to "Duck Egg",
    "Ou de gâscă" to "Goose Egg",
    "Ou de prepeliță" to "Quail Egg",
    "Ou fiert" to "Boiled Egg",
    "Ou prăjit" to "Fried Egg",
    "Omuletă" to "Omelet",
    "Carne de Pui" to "Chicken Meat",
    "Piept de Pui" to "Chicken Breast",
    "Pulpe de Pui" to "Chicken Thighs",
    "Carne de Curcan" to "Turkey Meat",
    "Carne de Rață" to "Duck Meat",
    "Carne de Găină" to "Hen Meat",
    "Carne de Porc" to "Pork",
    "Carne de Porc slabă" to "Lean Pork",
    "Carne de Vițel" to "Veal",
    "Carne de Vită" to "Beef",
    "Carne de Bovina" to "Bovine Meat",
    "Carne de Mânz" to "Foal Meat",
    "Carne de Oaie" to "Mutton",
    "Carne de Iepure" to "Rabbit Meat",
    "Carne de Vânat" to "Game Meat",
    "Carne de Mistreț" to "Wild Boar Meat",
    "Carne de Căprior" to "Roe Deer Meat",
    "Icre de pește" to "Fish Roe",
    "Icre de Manț" to "Manț Roe",
    "Icre de hering" to "Herring Roe",
    "Icre negre" to "Black Caviar",
    "Sardine" to "Sardines",
    "Somon" to "Salmon",
    "Macrou" to "Mackerel",
    "Hering" to "Herring",
    "Cod" to "Cod",
    "Stimpan" to "Stimpan",
    "Știucă" to "Pike",
    "Caras" to "Crucian Carp",
    "Crap" to "Carp",
    "Lin" to "Tench",
    "Somn" to "Catfish",
    "Biban" to "Perch",
    "Păstrăv" to "Trout",
    "Cocktail de fructe" to "Fruit Cocktail",
    "Compot de fructe" to "Fruit Compote",
    "Gem de fructe" to "Fruit Jam",
    "Dulceață de fructe" to "Fruit Preserve",
    "Marmeladă" to "Marmalade",
    "Sirop de fructe" to "Fruit Syrup",
    "Zahăr" to "Sugar",
    "Zahăr pudră" to "Powdered Sugar",
    "Zahăr brun" to "Brown Sugar",
    "Fructoză" to "Fructose",
    "Glucoză" to "Glucose",
    "Miere" to "Honey",
    "Miere de salcâm" to "Acacia Honey",
    "Miere de tei" to "Linden Honey",
    "Miere de polifloră" to "Wildflower Honey",
    "Sirop de arțar" to "Maple Syrup",
    "Melasă" to "Molasses",
    "Biscuiți" to "Biscuits",
    "Biscuiți Populari" to "Plain Biscuits",
    "Biscuiți cu ciocolată" to "Chocolate Biscuits",
    "Biscuiți digestive" to "Digestive Biscuits",
    "Gașcă" to "Gașcă",
    "Covrigi cu mac" to "Poppy Seed Pretzels",
    "Covrigi simpli" to "Plain Pretzels",
    "Lipie" to "Flatbread",
    "Pită" to "Rustic Bread",
    "Plăcintă cu brânză" to "Cheese Pie",
    "Plăcintă cu mere" to "Apple Pie",
    "Plăcintădobrogeană" to "Dobrogean Pie",
    "Sarmale" to "Cabbage Rolls",
    "Mâncare de cartofi" to "Potato Stew",
    "Ciorbă de burtă" to "Tripe Soup",
    "Ciorbă de fasole" to "Bean Soup",
    "Ciorbă de legume" to "Vegetable Soup",
    "Supă de pui" to "Chicken Soup",
    "Supă de legume" to "Vegetable Broth",
    "Bors" to "Borscht",
    "Ciorbă de perisoare" to "Meatball Soup",
    "Zacusca de pește" to "Fish Zacusca",
    "Zacusca de legume" to "Vegetable Zacusca",
    "Leustean cu smantana" to "Lovage with Cream",
    "Mamaliga cu branza" to "Polenta with Cheese",
    "Mamaliga cu lapte" to "Polenta with Milk",
    "Jumări" to "Pork Cracklings",
    "Slănină" to "Cured Pork Fat",
    "Cârnați" to "Sausages",
    "Cârnați de Pleșcaiu" to "Pleșcoi Sausages",
    "Mititei" to "Grilled Minced Rolls",
    "Hamburger" to "Hamburger",
    "Hot Dog" to "Hot Dog",
    "Shaorma" to "Shawarma",
    "Döner Kebab" to "Doner Kebab",
    "Pizza Margherita" to "Margherita Pizza",
    "Pizza cu pepperoni" to "Pepperoni Pizza",
    "Sandwich" to "Sandwich",
    "Clătite" to "Pancakes",
    "Clătite cu brânză" to "Cheese Pancakes",
    "Gogoși" to "Doughnuts",
    "Cozonac" to "Sweet Bread Loaf",
    "Chec" to "Loaf Cake",
    "Prajitură cu ciocolată" to "Chocolate Cake",
    "Ecler" to "Eclair",
    "Amandine" to "Amandine Cake",
    "Ruladă" to "Swiss Roll",
    "Tort" to "Cake",
    "Salată de vinete" to "Eggplant Salad",
    "Salată de gud Strela" to "Salată de gud Strela",
    "Ic" to "Ic",
    "Salată de ardei copți" to "Roasted Pepper Salad",
    "Tzatziki" to "Tzatziki",
    "Hummus" to "Hummus",
    "Varză acră" to "Sauerkraut",
    "Murături" to "Pickles",
    "Castraveți murați" to "Pickled Cucumbers",
    "Gogonele" to "Pickled Green Tomatoes",
    "Ardei iuți murați" to "Pickled Hot Peppers",
    "Ciuperci murate" to "Pickled Mushrooms",
    "Măsline murate" to "Pickled Olives",
    "Ghiveci" to "Vegetable Stew",
    "Varză călită" to "Braised Cabbage",
    "Cartofi călită" to "Braised Potatoes",
    "Cartofi la cuptor" to "Oven-Baked Potatoes",
    "Cartofi gratinați" to "Gratin Potatoes",
    "Legume la grătar" to "Grilled Vegetables",
    "Legume fierte" to "Boiled Vegetables",
    "Legume înăbușite" to "Stewed Vegetables",
    "Batog de pește" to "Dried Fish",
    "File de pește" to "Fish Fillet",
    "Pate de ficat" to "Liver Pate",
    "Crudități" to "Raw Vegetables",
    "Aspic" to "Aspic",
    "Ruladă de curcan" to "Turkey Roll",
    "Ruladă de pui" to "Chicken Roll",
    "Chiftele" to "Meatballs",
    "Parjoale" to "Romanian Meat Patties",
    "Snitel de pui" to "Chicken Schnitzel",
    "Snitel de porc" to "Pork Schnitzel",
    "Cotlet de porc" to "Pork Chop",
    "Antricot" to "Entrecote",
    "Mușchi de porc" to "Pork Tenderloin",
    "Mușchi de vacă" to "Beef Tenderloin",
    "Coaste de porc" to "Pork Ribs",
    "Ceafă de porc" to "Pork Neck",
    "Schnitzel" to "Schnitzel",
    "Cartofi pai" to "Shoestring Fries",
    "Ostropel" to "Ostropel",
    "Musaca" to "Moussaka",
    "Tochitura" to "Tochitura",
    "Mici" to "Grilled Minced Rolls",
    "Crenvurști" to "Hot Dog Sausages",
    "Bacon" to "Bacon",
    "Șuncă" to "Ham",
    "Prosciutto" to "Prosciutto",
    "Salam" to "Salami",
    "Salam de Sibiu" to "Sibiu Salami",
    "Salam de Timișoara" to "Timișoara Salami",
    "Pastramă" to "Pastrami",
    "Carne uscată" to "Dried Meat",
    "Ceai negru" to "Black Tea",
    "Ceai verde" to "Green Tea",
    "Ceai de mușețel" to "Chamomile Tea",
    "Cafea" to "Coffee",
    "Cafea cu lapte" to "Coffee with Milk",
    "Cappuccino" to "Cappuccino",
    "Latte macchiato" to "Latte Macchiato",
    "Espresso" to "Espresso",
    "Răcoritoare" to "Soft Drinks",
    "Coca Cola" to "Coca-Cola",
    "Fanta" to "Fanta",
    "Sprite" to "Sprite",
    "Pepsi" to "Pepsi",
    "Suc de portocale" to "Orange Juice",
    "Suc de mere" to "Apple Juice",
    "Suc de struguri" to "Grape Juice",
    "Suc de roșii" to "Tomato Juice",
    "Suc de grepfrut" to "Grapefruit Juice",
    "Nectar de piersici" to "Peach Nectar",
    "Nectar de caise" to "Apricot Nectar",
    "Bere" to "Beer",
    "Bere blondă" to "Lager Beer",
    "Bere neagră" to "Dark Beer",
    "Vin roșu" to "Red Wine",
    "Vin alb" to "White Wine",
    "Vin rose" to "Rose Wine",
    "Vin spumant" to "Sparkling Wine",
    "Tuica" to "Plum Brandy",
    "Palinca" to "Palinca",
    "Rachiu" to "Brandy",
    "Coniac" to "Cognac",
    "Vodka" to "Vodka",
    "Whiskey" to "Whiskey",
    "Bautura energizanta" to "Energy Drink",
    "Isostar" to "Isostar",
    "Gatorade" to "Gatorade",
    "Apa" to "Water",
    "Apa minerala" to "Mineral Water"
)
